---
title: "Gapminder Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=TRUE}
library(flexdashboard)
library(leaflet)
library(rnaturalearth)
library(dplyr)
library(sf)
library(shiny)
library(ggplot2)
library(gapminder)
```

Column {data-width = 650}
-----------------------------------------------------------------------

```{r}

# Color palette
pal <- colorNumeric("YlOrRd", domain = NULL)

# Load African country boundaries
africa <- ne_countries(continent = "Africa", returnclass = "sf")

selectInput(
  inputId = "I_dont_know_how_it_works",
  label = "Select Year:",
  choices = unique(gapminder$year)
)

renderLeaflet({
  
  africa_data <- gapminder |>
    filter(continent == "Africa",
         year == input$I_dont_know_how_it_works) 
  
  africa_map <- africa |>
    left_join(africa_data, by = c("name" = "country")) |>
    select(year, lifeExp)
  
  
  pal <- colorNumeric("YlOrRd", domain = NULL)
  
  leaflet(africa_map) |>
    addTiles() |>
    addPolygons(
      fillColor = ~pal(lifeExp),
      fillOpacity = 0.7
    ) |>
    addLegend(
      pal = pal,
      values = ~lifeExp,
      title = "wtf am I doing",
      position = "bottomleft"
    ) 
  
})
```
